config/routes.rb
Rails.application.routes.draw do
  root 'blogs#index'
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :blogs do
    collection do
      post :confirm
    end
  end
  resources :favorites, only: [:create, :destroy, :show]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :content, presence: true, length: { mininum: 1, maximum: 255 }

  belongs_to :user
  has_many :favorites ,dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 6 }
  validates :email ,uniqueness: true
  before_validation { email.downcase! }
  has_secure_password
  mount_uploader :image, ImageUploader
  validates :image, presence: true
  has_many :blogs ,dependent: :destroy
  has_many :favorite ,dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required
  

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
  def index
    @blogs = Blog.all
    @users = current_user
  end

  def new
    @blog = Blog.new
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    user = current_user #confirmation_mailer.rbで使うために定義
    if @blog.save
      ConfirmationMailer.confirmation_email(user).deliver
      redirect_to blogs_path, notice: "投稿しました！"
    else
      render :new, notice: "投稿できませんでした"
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = current_user.blogs.find(params[:id])
    if @blog.user_id != current_user.id
      redirect_to blogs_path, notice: "他人の投稿は編集できません！"
    end
  end

  def update
    @blog = current_user.blogs.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "編集しました！"
    else
      render :edit, notice: "編集できませんでした"
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    if @blog.destroy
      redirect_to blogs_path, notice: "削除しました！"
    else
      render :index, notice: "削除できませんでした"
    end
  end

  private
  def blog_params
    params.require(:blog).permit(:content, :image, :image_cache)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @blog = Blog.find(params[:blog])
    if @blog.user_id != current_user.id #自分の投稿にはいいねできないようにする
      @favorite = Favorite.create(user_id: current_user.id, blog_id: @blog.id) #いいねを押したらその投稿のidを取得して、@favoriteに代入
      redirect_to blogs_path, notice: "いいねしました"
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @favorite = Favorite.find_by(user_id: current_user.id, blog_id: @blog.id)
    @favorite.destroy
    redirect_to blogs_path, notice: "いいねを取り消しました"

  end

  def show
    favorites = Favorite.where(user_id: current_user.id).pluck(:blog_id)
    @favorite_list = Blog.find(favorites)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create, :show]
  def new
    
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id]=@user.id
      redirect_to user_path(@user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました。メールアドレスもしくはパスワードが違います。'
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,:image, :image_cache)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create, :show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash.now[:notice]= 'ユーザー登録が完了しました'
      redirect_to user_path(@user.id)
    else
      flash.now[:danger] = 'ユーザー登録に失敗しました'
      render :new
    end
  end

  def edit
    @user=User.find(params[:id])
    if @user.id != current_user.id
      redirect_to blogs_path, notice: "他人の投稿及びプロフィールは編集できません！"
    end

  end
    

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), flash:{notice: "アカウント情報を更新しました!"}
    else
      flash.now[:danger] = 'アカウント情報の更新に失敗しました'
      render :edit
    end
  end


  def show
    @user = User.find(params[:id])

    
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,:image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user || @current_user= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<body class="img">
  <%= form_with(model: @blog, url: choose_new_or_edit, local: true) do |form| %>
    <% if @blog.errors.any? %>
    <div class="error_messages">
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </div>
    <% end %>

    <div class="blog">
      <%= form.label :content, "投稿内容", class: "content" %>
      <%= form.text_field :content, class: "text", placeholder: "内容を入力"%>
    </div>

    <div class="field" >
      <%= form.label :image %>
      <%= image_tag(@blog.image.url, size:"160x160") if @blog.image && @blog.image.url %>
      <%= form.file_field :image %>
      <%= form.hidden_field:image_cache  %>
    </div>

    <%= form.submit class:"btn btn-outline-primary"%>
    <%= link_to "戻る",  blogs_path%>
  <% end %>
<body>

app/views/blogs/confirm.html.erb
<h3>以下の内容で投稿してもよろしいですか？</h3>
<%= form_with(model: @blog, local: true) do |form| %>
  <%= image_tag(@blog.image.url, size:"160x160") if @blog.image && @blog.image.url%>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
    <p>投稿内容:<%= @blog.content %></p>
    <p>投稿画像:<%= @blog.image %></p>
  <%= form.submit  "投稿する" %>
<%end%>

<%= form_with(model:@blog, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= link_to "戻る", :back%>
<% end %>

app/views/blogs/edit.html.erb
<h1>編集画面</h1>
<%= render 'form'%>

app/views/blogs/index.html.erb
<body class="index">
  <h1 class="title">insta</h1>
  <table class="table">
      <tr>
        <th>内容</th>
        <th></th>
      </tr>

    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.content %>
          <% if blog.image.present?%>
            <%= image_tag blog.image.url,size:"160x160" %></td>
          <% else %>
            <p>この投稿には画像はありません</p>
          <% end %>
          <td>
            <% if blog.user == current_user %>
              <%= link_to "詳細の確認", blog_path(blog.id)%>
              <%= link_to "ツイートの編集", edit_blog_path(blog.id), data: {confirm: "本当に編集してもいいですか？"}%>
              <%= link_to "ツイートを削除", blog_path(blog.id),  method: :delete,data: {confirm: "本当に削除してもいいですか？"}%>
            <% else %>
              <%= render partial: "favorites/favorite", locals: { blog: blog } %> 
            <% end %>
            <p>ユーザーネーム:<%= blog.user.name%></p>
          </td>
      </tr>
    <% end %>


    <%= link_to "新しく投稿する", new_blog_path, class: "btn btn-light"%>
  </table>
</body>

app/views/blogs/new.html.erb
<h1>内容入力画面</h1>
<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>詳細画面</h1>
<p>内容:<%= @blog.content%></p>
<p>
<strong>Image</strong>
<% if @blog.image?%>
  <%= image_tag @blog.image.url, size:"160x160" %>
<%else%>
  <p>この投稿に画像はありません</p>
<%end%>
</p>
<%= link_to '戻る', blogs_path%>

app/views/favorites/_favorite.html.erb
<div id="favorite" data-id="<%= blog.id %>">
  <% if !Favorite.exists?(user:current_user, blog_id: blog.id)%>
    <%= link_to favorites_path(blog: blog), method: :post, class: "favorite-btn favorite-post" do %>
      <i class="far fa-thumbs-up"></i>
        <span>いいね！</span>
        <%= blog.favorites.length %>
    <% end %>  
  <% else %>
    <%= link_to favorite_path(blog), method: :delete, class: "favorite-btn favorite-delete"  do %>
      <i class="far fa-thumbs-up"></i> 
      <span>取り消す</span>
      <%= blog.favorites.length %>
    <% end %>
  <% end %>
</div>

app/views/favorites/show.html.erb
<h1>お気に入り一覧</h1>
<% if @favorite_list.present?%>
    <% @favorite_list.each do | favorite |%>
        <tr>
            <td>・<%= favorite.content %>
            <% if favorite.image.present?%>
                <%= image_tag favorite.image.url,size:"160x160" %></td>
            <% else %>
                <p>この投稿には画像はありません</p>
            <% end %>
        </tr>
    <% end %>
<%else%>
    <p>いいねした投稿はありません</p>
<%end%>

<p><%= link_to "戻る", blogs_path%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Insta</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <%if logged_in?%>
      <%= link_to 'Profile', user_path(current_user.id)%>
      <%= link_to 'Logout',session_path(current_user.id),method: :delete %>
      <%= link_to 'profile_edit',edit_user_path(current_user.id)%>
      <%= link_to 'favorites',favorite_path(current_user.id)%>
    <%else%>
      <%= link_to 'Signup',new_user_path%>
      <%= link_to 'Login',new_session_path%>
    <% end %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
	<div class="row login_box">
	      <div class="col-md-12 col-xs-12 login_control">
        <div class="outter"></div>   
          <%= form_with(model: @user, local: true) do |f| %>
            <div class="col-md-12 col-xs-12" align="center">
              <p>
                <strong>Image:</strong>
                <%= image_tag @user.image.url, size:"160x160" %>
              </p>
              <%= f.label :image, class:"image-circle"%>
              <%= f.file_field :image, class:"image-circle"%>
            </div>

            <div class="control">
              <%= f.label :name, class:"label"%>
              <%= f.text_field :name, class: "form-control", placeholder: "Name"%>
            </div>

            <div class="control">
              <%= f.label :email, class:"label" %>
              <%= f.email_field :email, class: "form-control", placeholder: "Email"%>
            </div>
            
            <div class="control">
              <%= f.label :password, class:"label" %>
              <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
            </div>

            <div class="control">
              <%= f.label :password_confirmation, class:"label" %>
              <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password_Confirmation" %>
            </div>
            <div align="center">
              <%= f.submit "Update Account!", class:"btn btn-primary"%>
              <%= link_to "戻る", user_path%>
            </div>
          <% end %>  
        </div>
    </div>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%# <link href='http://fonts.googleapis.com/css?family=Raleway:400,200' rel='stylesheet' type='text/css'> %>

<div class="container">
	<div class="row login_box">
	      <div class="col-md-12 col-xs-12 login_control">
        <div class="outter"></div>   
          <%= form_with(model: @user, local: true) do |f| %>
            <div class="col-md-12 col-xs-12" align="center">
              <%= f.label :image, class:"image-circle"%>
              <%= f.file_field :image, class:"image-circle"%>
            </div>

            <div class="control">
              <%= f.label :name, class:"label"%>
              <%= f.text_field :name, class: "form-control", placeholder: "Name"%>
            </div>

            <div class="control">
              <%= f.label :email, class:"label" %>
              <%= f.email_field :email, class: "form-control", placeholder: "Email"%>
            </div>
            
            <div class="control">
              <%= f.label :password, class:"label" %>
              <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
            </div>

            <div class="control">
              <%= f.label :password_confirmation, class:"label" %>
              <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password_Confirmation" %>
            </div>
            <div align="center">
              <%= f.submit "Create Account!", class:"btn btn-primary"%>
            </div>
          <% end %>  
        </div>
    </div>
</div>

app/views/users/show.html.erb
<%= flash[:notice]%>

<div class="text-center" >
  <p>
    <strong>Image:</strong>
    <%= image_tag @user.image.url,size:"160x160"%>
  </p>

  <h1><%= @user.name %>のページ</h1>

  <p>メールアドレス: <%= @user.email %></p>
  
</div>